# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dda9af3bcd29b3c368a2490cf2bd5eefae3d21e39533c991ecdfb1f32139f0c80beba94fd12222ef3eaceb067369919b5b8f577c6c1ee5785a5cf76e5fa7af2

test:
  secret_key_base: 84db30cfe0e2e3184e8ca8edaaa59bf28a670bcf154491aa49802e6dba46eaa26939b8b4e91c0af07c48139b3f2b92f5f5657454ee9c402aa46be953391316a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
